### ISSUE TITLE
Unicode issues

### ISSUE THREAD

**Issue by ablwr** [DocNow/storified#8]
Hey! Ran this but initially received an error (an apparently `classic!` Python error) related to Unicode conversion issues.

The trace:

```
  File "/usr/local/bin/storified.py", line 65, in download_file
    open(path, "w").write(resp.text)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 2927: ordinal not in range(128)
```

I fixed this locally but in a hacky-kind-of-way and ran it to get the job done, but I wanted to note in case someone with more expertise with the codebase would like to fix it properly.

I'm running macOS Sierra and this ran with Python 2.7.

**Comment by edsu** [comment]
Thanks for giving it a whirl! Let me make sure the latest version is pushed to GitHub. I thought I fixed that in #7.

**Comment by edsu** [comment]
Ahh it hasn't been released yet. I'll fix that shortly.

**Comment by ablwr** [comment]
😎 👍

**Comment by ablwr** [comment]
Ahhhaha this is essentially the same fix I did! https://github.com/DocNow/storified/commit/dbd73da9cb3b1fd44c831ea1aa2b75366659c72f 😅

**Comment by edsu** [comment]
Ok, give v0.0.8 a try, which is now on PyPI. It should also download images, js and css and rewrite the html to use them instead of the network resources which will disappear when storify.com goes offline.

**Comment by ablwr** [comment]
Coooooooooool.
